name: CI - Build and Push Docker Image Then Update K8s Manifest

on:
  push:
    branches: [ main ]

env:
  # Use secrets for sensitive data
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: "app-images" # The name we gave it in Terraform
  SERVICE_NAME: "microservice-a"
  # The repo with the Kubernetes manifests
  #MANIFESTS_REPO: ${{ github.repository_owner }}/gke-gitops-showcase/microservice-a-manifests

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-push:
    name: Build, Push and Update Manifests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Docker configure-auth'
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        # Use the first 7 characters of the commit SHA as the image tag
        IMAGE_TAG=${{ github.sha }}

        # Construct the full image URL
        IMAGE_URL="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.SERVICE_NAME }}:${IMAGE_TAG}"

        # Build the image
        docker build -t $IMAGE_URL .

        # Push the image
        docker push $IMAGE_URL

        # Save the image URL to a file to pass to the next step
        #echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

    # - name: Update K8s Manifest
    #   run: |
    #     echo "--- Checking out manifests repository ---"
    #     # Use a Personal Access Token (PAT) to checkout the manifests repo
    #     git clone https://${{ secrets.CICD_PAT }}@github.com/${{ env.MANIFESTS_REPO }}.git

    #     # Navigate into the cloned repo
    #     cd microservice-a-manifests

    #     echo "--- Updating image tag in deployment.yaml ---"
    #     # Use yq to safely update the YAML file
    #     # Install yq first
    #     sudo wget https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

    #     yq e '.spec.template.spec.containers[0].image = "${{ env.IMAGE_URL }}"' -i deployment.yaml

    #     echo "--- Committing and pushing changes ---"
    #     git config --global user.name "GitHub Actions CI"
    #     git config --global user.email "ci@github.actions"
    #     git add deployment.yaml
    #     # Check if there are changes to commit
    #     git diff --staged --quiet || git commit -m "ci: Update image to ${{ env.IMAGE_URL }}"
    #     git push